### ISSUE TITLE
Exception raised in example client

### ISSUE THREAD

**Issue by dylanholmes** [griptape-ai/griptape-cli#28]
When running the skatepark emulator client example, I see the following error in the client:

```txt
Traceback (most recent call last):
  File "/Users/dylan/Documents/managed-structure-example/example-client/client.py", line 108, in <module>
    print(run_structure("What is 123 * 34, 23 / 12.3, and 9 ^ 4?"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dylan/Documents/managed-structure-example/example-client/client.py", line 97, in run_structure
    return structure_run["output"]["value"] if "output" in structure_run else None
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

And this error in the server:
```txt
INFO:     127.0.0.1:58299 - "POST /api/structure-runs/fd876ff813a448af98bd58ab4bad71b1/events HTTP/1.1" 422 Unprocessable Entity
```

I'm guessing that the API schema has diverged from what is expected by the example client.

**Comment by SavagePencil** [comment]
After digging into this, we see that the Skatepark emulator isn't processing batched events properly. Need to add that functionality.

**Comment by SavagePencil** [comment]
https://github.com/griptape-ai/griptape-cli/pull/30
